MagicTracker/Controllers/CollectionController.cs
using MagicTracker.Models;
using MagicTracker.Models.CardApi;
using MagicTracker.Models.Deck;
using MagicTracker.Services;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MagicTracker.Controllers
{
    [Authorize]
    public class CollectionController : Controller
    {

        [HttpPost]
        [ValidateAntiForgeryToken]
        private CardService CreateCardService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CardService(userId);
            return service;
        }
        // GET: Collection
        public ActionResult Index()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CardService(userId);
            var model = service.GetCollection();
            service.GetAllDecksDictionary();
            return View(model);
        }
        public ActionResult Available()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CardService(userId);
            var model = service.GetAvailable();
            return View(model);
        }

        public ActionResult IndexEdit()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CardService(userId);
            var model = service.GetCollection();
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult IndexEdit(CollectionItem[] collectionItems)
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CardService(userId);
            foreach (CollectionItem collectionItem in collectionItems)
            {
                var model = new CardEdit
                {
                    CardId = collectionItem.CardId,
                    Name = collectionItem.Name,
                    Printing = collectionItem.Printing,
                    CardCondition = collectionItem.CardCondition,
                    IsFoil = collectionItem.IsFoil,
                    InUse = collectionItem.InUse,
                    ForTrade = collectionItem.ForTrade,
                    DeckId = collectionItem.DeckId,
                    MultiverseId = collectionItem.MultiverseId,
                    CardApiId = collectionItem.CardApiId
                };
                service.UpdateCard(model);
            }
            return RedirectToAction("Index");
        }



        //GET
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CardCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = CreateCardService();
            var resultId = service.CreateCard(model);


            if (resultId != -1)
            {
                TempData["SaveResult"] = "Your card was created.";
                return RedirectToAction("CardEdit", new { id = resultId });
            };

            ModelState.AddModelError("", "Card could not be found.");
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = CreateCardService();
            var model = svc.GetCardById(id);

            return View(model);
        }

        public ActionResult CardDetails(int id)
        {
            var service = CreateCardService();
            ApiCardView model = new ApiCardView();
            model.Card = service.GetCardById(id);
            model.Api = service.GetCardApiItem(model.Card.CardApiId.Value);
            if (model.Card.DeckId != null) { model.DeckName = service.GetDeckItem(model.Card.DeckId.Value).Name; }
            else model.DeckName = "No Deck";
            
            return View(model);
        }

        [ActionName("CardEdit")]
        public ActionResult CardEdit(int id)
        {
            var service = CreateCardService();
            ApiCardView model = new ApiCardView();
            model.Card = service.GetCardById(id);
            model.Api = service.GetCardApiItem(model.Card.CardApiId.Value);
            model.DeckDict = service.GetAllDecksDictionary();
            return View(model);
        }

        [HttpPost]
        [ActionName("CardEdit")]
        [ValidateAntiForgeryToken]
        public ActionResult CardEdit(ApiCardView cardView)
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CardService(userId);
            cardView.Api = service.GetCardApiItem(cardView.Card.CardApiId.Value);

            var setDict = JsonConvert.DeserializeObject<Dictionary<string, int>>(cardView.Api.MultiSetDict);
            var model = new CardEdit
            {
                CardId = cardView.Card.CardId,
                Name = cardView.Card.Name,
                Printing = cardView.Card.Printing,
                CardCondition = cardView.Card.CardCondition,
                IsFoil = cardView.Card.IsFoil,
                InUse = cardView.Card.InUse,
                ForTrade = cardView.Card.ForTrade,
                DeckId = cardView.Card.DeckId,
                MultiverseId = setDict[cardView.Card.Printing],
                CardApiId = cardView.Card.CardApiId
            };
            if(model.DeckId == -1) { model.DeckId = null; }
                service.UpdateCard(model);
            
            return RedirectToAction("Index");
        }

        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CreateCardService();
            var model = svc.GetCardById(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeletePost(int id)
        {
            var service = CreateCardService();

            service.DeleteCard(id);

            TempData["SaveResult"] = "Your card was deleted";

            return RedirectToAction("Index");
        }
        
        [ActionName("CardDelete")]
        public ActionResult CardDelete(int id)
        {
            var service = CreateCardService();
            ApiCardView model = new ApiCardView();
            model.Card = service.GetCardById(id);
            model.Api = service.GetCardApiItem(model.Card.CardApiId.Value);
            if (model.Card.DeckId != null) { model.DeckName = service.GetDeckItem(model.Card.DeckId.Value).Name; }
            else model.DeckName = "No Deck";

            return View(model);
        }

        [HttpPost]
        [ActionName("CardDelete")]
        [ValidateAntiForgeryToken]
        public ActionResult CardDeletePost(int id)
        {
            var service = CreateCardService();

            service.DeleteCard(id);

            TempData["SaveResult"] = "Your card was deleted";

            return RedirectToAction("Index");
        }



        public ActionResult DeckIndex()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CardService(userId);
            var model = service.GetAllDeckItems();
            return View(model);
        }

        public ActionResult DeckCreate()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeckCreate(DeckCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = CreateCardService();
            var resultId = service.CreateDeck(model);
            if ( resultId != -1)
            {
                TempData["SaveResult"] = "Your Deck was created.";
                return RedirectToAction("DeckImportEdit", new { id = resultId });
            };
            ModelState.AddModelError("", "Card could not be found.");

            return View(model);
        }

        public ActionResult DeckDetails(int id)
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CardService(userId);
            var model = service.GetDeck(id);
            return View(model);
        }

        public ActionResult DeckDetailsPartial(int id)
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CardService(userId);
            var model = service.GetDeck(id);
            return PartialView("_DeckPartial",model);
        }

        public ActionResult DeckEdit(int id)
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CardService(userId);
            var model = service.GetDeck(id);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeckEdit(CollectionItem[] collectionItems)
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new CardService(userId);
            foreach (CollectionItem collectionItem in collectionItems)
            {
                var model = new CardEdit
                {
                    CardId = collectionItem.CardId,
                    Name = collectionItem.Name,
                    Printing = collectionItem.Printing,
                    CardCondition = collectionItem.CardCondition,
                    IsFoil = collectionItem.IsFoil,
                    InUse = collectionItem.InUse,
                    ForTrade = collectionItem.ForTrade,
                    DeckId = collectionItem.DeckId,
                    MultiverseId = collectionItem.MultiverseId,
                    CardApiId = collectionItem.CardApiId
                };
                service.UpdateCard(model);
            }
            return RedirectToAction("DeckIndex");
        }

MagicTracker/Views/Collection/Available.cshtml
@model IEnumerable<MagicTracker.Models.CollectionItem>

@{
    ViewBag.Title = "Available";
}

<h2>Available Cards</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
@if (TempData.ContainsKey("SaveResult"))
{
    <div class="alert alert-success fade in" role="alert">

        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
        @TempData["SaveResult"]
    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CardId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        var imgLink = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=" + item.MultiverseId.ToString() + "&type=card";
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CardId)
            </td>
            <td>
                <a href="@Url.Action("Details", "Collection", new {id = item.CardId})" rel="popover" data-img="@imgLink">@Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td>
                @Html.ActionLink("Edit", "CardEdit", new {id = item.CardId }) |
                @Html.ActionLink("Details", "CardDetails", new {id = item.CardId}) |
                @Html.ActionLink("Delete", "Delete", new {id = item.CardId})
            </td>
        </tr>
    }

</table>

MagicTracker/Views/Collection/CardDelete.cshtml
@model MagicTracker.Models.CardApi.ApiCardView

@{
    ViewBag.Title = "CardDelete";
    var imgLink = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=" + Model.Card.MultiverseId.ToString() + "&type=card";
    var gathererLink = "http://gatherer.wizards.com/pages/card/Details.aspx?multiverseid=" + Model.Card.MultiverseId.ToString() + "&type=card";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Card</h4>
    <hr />
    <section>
        <section style="width:50%; float: left">
            <dl class="dl-horizontal">

                <dt>
                    @Html.DisplayNameFor(model => model.Card.Name)
                </dt>

                <dd>
                    <a href="@gathererLink" rel="popover" data-img="@imgLink">@Html.DisplayFor(model => model.Card.Name)</a>
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Card.Printing)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Card.Printing)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DeckName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DeckName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Card.CardCondition)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Card.CardCondition)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Card.IsFoil)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Card.IsFoil)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Card.InUse)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Card.InUse)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Card.ForTrade)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Card.ForTrade)
                </dd>

            </dl>
        </section>
        <section style="width:50%; float: right">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Api.ManaCost)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Api.ManaCost)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Api.Colors)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Api.Colors)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Api.Type)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Api.Type)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Api.Subtypes)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Api.Subtypes)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Api.Text)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Api.Text)
                </dd>
            </dl>
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions no-color">
                    <input type="submit" value="Delete" class="btn btn-default" /> |
                    @Html.ActionLink("Back to List", "Index")
                </div>
            }
        </section>
    </section>


</div>

MagicTracker/Views/Collection/CardDetails.cshtml
@model MagicTracker.Models.CardApi.ApiCardView

@{
    ViewBag.Title = "CardDetails";
}

<h2>Details</h2>

<div>
    <h4>Card</h4>
    <hr />
    <section>
        <section style="width:50%; float: left">
            <dl class="dl-horizontal">

                <dt>
                    @Html.DisplayNameFor(model => model.Card.Name)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Card.Name)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Card.Printing)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Card.Printing)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.DeckName)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.DeckName)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Card.CardCondition)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Card.CardCondition)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Card.IsFoil)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Card.IsFoil)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Card.InUse)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Card.InUse)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Card.ForTrade)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Card.ForTrade)
                </dd>

            </dl>
        </section>
        <section style="width:50%; float: right">
            <dl class="dl-horizontal">
                <dt>
                    @Html.DisplayNameFor(model => model.Api.ManaCost)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Api.ManaCost)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Api.Colors)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Api.Colors)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Api.Type)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Api.Type)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Api.Subtypes)
                </dt>

                <dd>
                    @Html.DisplayFor(model => model.Api.Subtypes)
                </dd>

                <dt>
                    @Html.DisplayNameFor(model => model.Api.Text)
                </dt>
                <dd>
                    @Html.DisplayFor(model => model.Api.Text)
                </dd>
            </dl>
            <p>
                @Html.ActionLink("Edit", "CardEdit", new { id = Model.Card.CardId }) |
                @Html.ActionLink("Back to List", "Index")
            </p>
        </section>
    </section>
</div>

MagicTracker/Views/Collection/CardEdit.cshtml
@model MagicTracker.Models.CardApi.ApiCardView
@using Newtonsoft.Json

@{
    ViewBag.Title = "CardEdit";
}

<h2>Card Import Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <table class="table">
            <tr>
                <th>Name</th>
                <th>Set</th>
                <th>Card Condition</th>
                <th>Foil</th>
                <th>In Use</th>
                <th>For Trade</th>
                <th>Deck</th>
            </tr>
            @Html.HiddenFor(model => model.Card.MultiverseId)
            @Html.HiddenFor(model => model.Card.CardApiId)
            @Html.HiddenFor(model => model.Card.CardId)
            @Html.HiddenFor(model => model.Card.Name)

            @Html.HiddenFor(model => model.Api)
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <tr>
                <td>
                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.DisplayFor(model => model.Card.Name, new { htmlAttributes = new { @class = "form-control" } })
                        </div>
                    </div>
                </td>

                <td>
                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Card.Printing,
                            new SelectList(JsonConvert.DeserializeObject<Dictionary<string, string>>(Model.Api.SetNameDict), "Key", "Value"),
                            new { htmlAttributes = new { @class = "form-control" } }
                            )
                        </div>
                    </div>
                </td>

                <td>
                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Card.CardCondition,
                                new SelectList(Enum.GetValues(typeof(MagicTracker.Data.Condition))),
                                new { htmlAttributes = new { @class = "form-control" } }
                                )
                            @Html.ValidationMessageFor(model => model.Card.CardCondition, "", new { @class = "text-danger" })
                        </div>
                    </div>
                </td>

                <td>
                    <div class="form-group">
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.Card.IsFoil)
                                @Html.ValidationMessageFor(model => model.Card.IsFoil, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </td>

                <td>
                    <div class="form-group">
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.Card.InUse)
                                @Html.ValidationMessageFor(model => model.Card.InUse, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </td>

                <td>
                    <div class="form-group">
                        <div class="col-md-10">
                            <div class="checkbox">
                                @Html.EditorFor(model => model.Card.ForTrade)
                                @Html.ValidationMessageFor(model => model.Card.ForTrade, "", new { @class = "text-danger" })
                            </div>
                        </div>
                    </div>
                </td>

                <td>
                    <div class="form-group">
                        <div class="col-md-10">
                            @Html.DropDownListFor(model => model.Card.DeckId,
                            new SelectList(Model.DeckDict, "Value", "Key"),
                            new { htmlAttributes = new { @class = "form-control" } }
                            )
                        </div>
                    </div>
                </td>
            </tr>
        </table>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MagicTracker/Views/Collection/Create.cshtml
@model MagicTracker.Models.CardCreate

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>CardCreate</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.CardName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CardName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CardName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MagicTracker/Views/Collection/DeckCreate.cshtml
@model MagicTracker.Models.Deck.DeckCreate

@{
    ViewBag.Title = "DeckCreate";
}

<h2>New Deck</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Create New Deck</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CardListString, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10" >
                @Html.TextAreaFor(model => model.CardListString, new { htmlAttributes = new { @class = "form-control", id= "test" } })
                @Html.ValidationMessageFor(model => model.CardListString, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "DeckIndex")
</div>

<link href="~/Content/styles.css" rel="stylesheet" type="text/css" />

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

MagicTracker/Views/Collection/DeckDelete.cshtml
@model MagicTracker.Models.Deck.DeckItem

@{
    ViewBag.Title = "DeckDelete";
}

<h2>DeleteDeck</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DeckItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DeckId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeckId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CardListString)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CardListString)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "DeckIndex")
        </div>
    }
</div>

MagicTracker/Views/Collection/DeckDeleteComplete.cshtml
@model MagicTracker.Models.Deck.DeckItem

@{
    ViewBag.Title = "DeckDeleteComplete";
}

<h2>DeckDeleteComplete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>DeckItem</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DeckId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeckId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.OwnerId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.OwnerId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CardListString)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CardListString)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to Decks", "DeckIndex")
        </div>
    }
</div>

MagicTracker/Views/Collection/DeckIndex.cshtml
@model IEnumerable<MagicTracker.Models.Deck.DeckItem>

@{
    ViewBag.Title = "DeckIndex";
}

<h2>Your Decks</h2>

<p>
    @Html.ActionLink("Create New", "DeckCreate")
</p>



@{ int i = 0;}
@foreach (var item in Model)
{
<div class="accordion" id="accordion_@i">
    <div class="card">
        <div class="card-header" id="card_@i">
            <h4 class="mb-0">
                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne_@i" aria-expanded="false" aria-controls="collapseOne" href="#collapseOne_@i">
                    @Html.DisplayFor(modelItem => item.Name)
                </button>
            </h4>
        </div>

        <div id="collapseOne_@i" class="collapse" aria-labelledby="card_@i" data-parent="accordion_@i">
            <div class="card-body">
                @Html.ActionLink("Edit", "DeckImportEdit", new { id = item.DeckId }) |
                @Html.ActionLink("Delete Deck", "DeckDelete", new { id = item.DeckId }) |
                @Html.ActionLink("Delete Cards", "DeckDeleteComplete", new { id = item.DeckId })|
                @{Html.RenderAction("DeckDetailsPartial", new { id = item.DeckId });}
            </div>
        </div>
    </div>
</div>
i++;
}

MagicTracker/Views/Collection/Index.cshtml
@model IEnumerable<MagicTracker.Models.CollectionItem>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create") |
    @Html.ActionLink("Edit Collection", "IndexEdit", "Collection") |
    @Html.ActionLink("Available Cards", "Available", "Collection")
</p>
@if (TempData.ContainsKey("SaveResult"))
{
    <div class="alert alert-success fade in" role="alert">

        <button type="button" class="close" data-dismiss="alert">
            <span>&times;</span>
        </button>
        @TempData["SaveResult"]
    </div>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CardId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        var imgLink = "http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=" + item.MultiverseId.ToString() + "&type=card";
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CardId)
            </td>
            <td>
                <a href="@Url.Action("CardDetails", "Collection", new {id = item.CardId})" rel="popover" data-img="@imgLink">@Html.DisplayFor(modelItem => item.Name)</a>
            </td>
            <td>
                @Html.ActionLink("Edit", "CardEdit", new {id = item.CardId }) |
                @Html.ActionLink("Details", "CardDetails", new {id = item.CardId}) |
                @Html.ActionLink("Delete", "CardDelete", new {id = item.CardId})
            </td>
        </tr>
    }

</table>